[package]
name = "key-recorder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "1.0.0"
chrono = "0.4.19"
ctrlc = "3.2.1"